---
  - name: Enable IPv4 forwarding
    hosts: k8s-cluster

    tasks:
    - name: Enable IPv4 in sysctl.conf file
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes