---
  # Playbook that runs on all hosts
  - hosts: All
    - import_playbook: install-updates-upgrades.yml
    - import_playbook: config-disable-swap.yml
    - import_playbook: config-ip-forward.yml
    - import_playbook: install-chrootkit.yml
    - import_playbook: install-htop.yml
    - import_playbook: install-iftop.yml
    - import_playbook: install-lynis.yml
    - import_playbook: install-ncdu.yml
    - import_playbook: install-python.yml
    - import_playbook: install-rkhunter.yml