---
  # Playbook that runs on all hosts
  - hosts: k8s-cluster
    become: true
    tasks:
      - name: Scan and register VM's
        command: "ssh-keyscan {{ item }}"
        register: "host_keys"
        changed_when: false
        with_items: '{{ groups.all }}'
        delegate_to: localhost
        become: false
      - name: Write keys
        template:
          src: ssh-hosts.j2"
          dest: ".ssh/know_hosts"