---
  # Playbook that runs on all hosts
  - import_tasks: install-updates-upgrades.yml
  - import_tasks: config-disable-swap.yml
  - import_tasks: config-ip-forward.yml
  - import_tasks: install-chrootkit.yml
  - import_tasks: install-htop.yml
  - import_tasks: install-iftop.yml
  - import_tasks: install-lynis.yml
  - import_tasks: install-ncdu.yml
  - import_tasks: install-python.yml
  - import_tasks: install-rkhunter.yml